version: "3.8"
services:
  avail-da-server:
    build: .
    env_file:
      - .env
    environment:
      - ADDR
      - PORT
      - AVAIL_RPC
      - AVAIL_SEED
      - AVAIL_APPID
      - AVAIL_TIMEOUT
    ports:
      - "${PORT}:${PORT}"
      - "8080:8080"
      - "433:433"
