version: "3.8"
services:
  avail-da-server:
    build: .
    environment:
      - OP_PLASMA_AVAIL_DA_SERVER_ADDR=${ADDR:-0.0.0.0}
      - OP_PLASMA_AVAIL_DA_SERVER_PORT=${PORT:-8080}
      - OP_PLASMA_AVAIL_DA_SERVER_AVAIL_RPC=${AVAIL_RPC:-http://host.docker.internal:9933}
      - OP_PLASMA_AVAIL_DA_SERVER_AVAIL_SEED=${AVAIL_SEED}
      - OP_PLASMA_AVAIL_DA_SERVER_AVAIL_APPID=${AVAIL_APPID:-1}
      - OP_PLASMA_AVAIL_DA_SERVER_TURBODA=${TURBODA:-false}
      - OP_PLASMA_AVAIL_DA_SERVER_TURBODA_URL=${TURBODA_URL}
      - OP_PLASMA_AVAIL_DA_SERVER_TURBODA_KEY=${TURBODA_KEY}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"